networks:
  - name: datacentre_ovs_419
    physical_network: datacentre
    segmentation_id: 419
    external: true
    allocation_pool_start: 10.35.185.18
    allocation_pool_end: 10.35.185.29
    cidr: 10.35.185.16/28
    enable_dhcp: false
    gateway_ip: 10.35.185.30
    router_name: router1
    port_type: normal
    ip_version: 4
    network_type: vlan

dns_nameservers:
  - 10.35.28.28
  - 8.8.8.8
tempest_tests:
  - tempest_plugin.tests.scenario.test_nfv_dpdk_usecases.TestDirectScenarios.test_basic_network
  - tempest.api.compute.admin.test_flavors.FlavorsAdminTestJSON.test_create_flavor_using_string_ram
